export default {

places : [
  {
    id: 0,
    destination: "Antananarivo",
    departureTime: 1613397600,
    driverName: "Tom Cruise",
    driverContact: "034585514",
    estimatedDuration: "12h",
    breaks: "2",
    price: 20000,
    seats: [
      {
        id: 0,
        isAvailable: true,
        passengerFirstName: "",
        passengerLastName: "",
        passengerPhoneNumber: "",
        extraLuggage: false,
      },
      {
        id: 1,
        isAvailable: true,
        passengerFirstName: "",
        passengerLastName: "",
        passengerPhoneNumber: "",
        extraLuggage: false,
      },
      {
        id: 2,
        isAvailable: true,
        passengerFirstName: "",
        passengerLastName: "",
        passengerPhoneNumber: "",
        extraLuggage: false,
      },
      {
        id: 3,
        isAvailable: true,
        passengerFirstName: "",
        passengerLastName: "",
        passengerPhoneNumber: "",
        extraLuggage: false,
      },
      {
        id: 4,
        isAvailable: true,
        passengerFirstName: "",
        passengerLastName: "",
        passengerPhoneNumber: "",
        extraLuggage: false,
      },
      {
        id: 5,
        isAvailable: true,
        passengerFirstName: "",
        passengerLastName: "",
        passengerPhoneNumber: "",
        extraLuggage: false,
      },
      {
        id: 6,
        isAvailable: true,
        passengerFirstName: "",
        passengerLastName: "",
        passengerPhoneNumber: "",
        extraLuggage: false,
      },
      {
        id: 7,
        isAvailable: true,
        passengerFirstName: "",
        passengerLastName: "",
        passengerPhoneNumber: "",
        extraLuggage: false,
      },
      {
        id: 8,
        isAvailable: true,
        passengerFirstName: "",
        passengerLastName: "",
        passengerPhoneNumber: "",
        extraLuggage: false,
      },
      {
        id: 9,
        isAvailable: true,
        passengerFirstName: "",
        passengerLastName: "",
        passengerPhoneNumber: "",
        extraLuggage: false,
      },
      {
        id: 10,
        isAvailable: false,
        passengerFirstName: "",
        passengerLastName: "",
        passengerPhoneNumber: "",
        extraLuggage: false,
      },
      {
        id: 11,
        isAvailable: false,
        passengerFirstName: "",
        passengerLastName: "",
        passengerPhoneNumber: "",
        extraLuggage: false,
      },
      {
        id: 12,
        isAvailable: false,
        passengerFirstName: "",
        passengerLastName: "",
        passengerPhoneNumber: "",
        extraLuggage: false,
      },
      {
        id: 13,
        isAvailable: false,
        passengerFirstName: "",
        passengerLastName: "",
        passengerPhoneNumber: "",
        extraLuggage: false,
      },
      {
        id: 14,
        isAvailable: false,
        passengerFirstName: "",
        passengerLastName: "",
        passengerPhoneNumber: "",
        extraLuggage: true,
      },
      {
        id: 15,
        isAvailable: true,
        passengerFirstName: "",
        passengerLastName: "",
        passengerPhoneNumber: "",
        extraLuggage: true,
      },
      {
        id: 16,
        isAvailable: true,
        passengerFirstName: "",
        passengerLastName: "",
        passengerPhoneNumber: "",
        extraLuggage: false,
      },
      {
        id: 17,
        isAvailable: true,
        passengerFirstName: "",
        passengerLastName: "",
        passengerPhoneNumber: "",
        extraLuggage: false,
      },
    ],
  },
  {
    id: 1,
    destination: "Antananarivo",
    departureTime: 1613480400,
    driverName: "James Bond",
    driverContact: "034585884",
    estimatedDuration: "12h",
    breaks: "2",
    price: 20000,
    seats: [
      {
        id: 0,
        isAvailable: false,
        passengerFirstName: "",
        passengerLastName: "",
        passengerPhoneNumber: "",
        extraLuggage: false,
      },
      {
        id: 1,
        isAvailable: false,
        passengerFirstName: "",
        passengerLastName: "",
        passengerPhoneNumber: "",
        extraLuggage: false,
      },
      {
        id: 2,
        isAvailable: false,
        passengerFirstName: "",
        passengerLastName: "",
        passengerPhoneNumber: "",
        extraLuggage: false,
      },
      {
        id: 3,
        isAvailable: false,
        passengerFirstName: "",
        passengerLastName: "",
        passengerPhoneNumber: "",
        extraLuggage: false,
      },
      {
        id: 4,
        isAvailable: false,
        passengerFirstName: "",
        passengerLastName: "",
        passengerPhoneNumber: "",
        extraLuggage: false,
      },
      {
        id: 5,
        isAvailable: false,
        passengerFirstName: "",
        passengerLastName: "",
        passengerPhoneNumber: "",
        extraLuggage: false,
      },
      {
        id: 6,
        isAvailable: false,
        passengerFirstName: "",
        passengerLastName: "",
        passengerPhoneNumber: "",
        extraLuggage: false,
      },
      {
        id: 7,
        isAvailable: false,
        passengerFirstName: "",
        passengerLastName: "",
        passengerPhoneNumber: "",
        extraLuggage: false,
      },
      {
        id: 8,
        isAvailable: false,
        passengerFirstName: "",
        passengerLastName: "",
        passengerPhoneNumber: "",
        extraLuggage: false,
      },
      {
        id: 9,
        isAvailable: false,
        passengerFirstName: "",
        passengerLastName: "",
        passengerPhoneNumber: "",
        extraLuggage: false,
      },
      {
        id: 10,
        isAvailable: false,
        passengerFirstName: "",
        passengerLastName: "",
        passengerPhoneNumber: "",
        extraLuggage: false,
      },
      {
        id: 11,
        isAvailable: false,
        passengerFirstName: "",
        passengerLastName: "",
        passengerPhoneNumber: "",
        extraLuggage: false,
      },
      {
        id: 12,
        isAvailable: false,
        passengerFirstName: "",
        passengerLastName: "",
        passengerPhoneNumber: "",
        extraLuggage: false,
      },
      {
        id: 13,
        isAvailable: false,
        passengerFirstName: "",
        passengerLastName: "",
        passengerPhoneNumber: "",
        extraLuggage: false,
      },
      {
        id: 14,
        isAvailable: false,
        passengerFirstName: "",
        passengerLastName: "",
        passengerPhoneNumber: "",
        extraLuggage: true,
      },
      {
        id: 15,
        isAvailable: false,
        passengerFirstName: "",
        passengerLastName: "",
        passengerPhoneNumber: "",
        extraLuggage: true,
      },
      {
        id: 16,
        isAvailable: false,
        passengerFirstName: "",
        passengerLastName: "",
        passengerPhoneNumber: "",
        extraLuggage: false,
      },
      {
        id: 17,
        isAvailable: false,
        passengerFirstName: "",
        passengerLastName: "",
        passengerPhoneNumber: "",
        extraLuggage: false,
      },
    ],
  },
  {
    id: 2,
    destination: "Antananarivo",
    departureTime: 1613570400,
    driverName: "Tom Cruise",
    driverContact: "034585177",
    estimatedDuration: "12h",
    breaks: "2",
    price: 20000,
    seats: [
      {
        id: 0,
        isAvailable: true,
        passengerFirstName: "",
        passengerLastName: "",
        passengerPhoneNumber: "",
        extraLuggage: false,
      },
      {
        id: 1,
        isAvailable: true,
        passengerFirstName: "",
        passengerLastName: "",
        passengerPhoneNumber: "",
        extraLuggage: false,
      },
      {
        id: 2,
        isAvailable: true,
        passengerFirstName: "",
        passengerLastName: "",
        passengerPhoneNumber: "",
        extraLuggage: false,
      },
      {
        id: 3,
        isAvailable: true,
        passengerFirstName: "",
        passengerLastName: "",
        passengerPhoneNumber: "",
        extraLuggage: false,
      },
      {
        id: 4,
        isAvailable: true,
        passengerFirstName: "",
        passengerLastName: "",
        passengerPhoneNumber: "",
        extraLuggage: false,
      },
      {
        id: 5,
        isAvailable: true,
        passengerFirstName: "",
        passengerLastName: "",
        passengerPhoneNumber: "",
        extraLuggage: false,
      },
      {
        id: 6,
        isAvailable: true,
        passengerFirstName: "",
        passengerLastName: "",
        passengerPhoneNumber: "",
        extraLuggage: false,
      },
      {
        id: 7,
        isAvailable: true,
        passengerFirstName: "",
        passengerLastName: "",
        passengerPhoneNumber: "",
        extraLuggage: false,
      },
      {
        id: 8,
        isAvailable: true,
        passengerFirstName: "",
        passengerLastName: "",
        passengerPhoneNumber: "",
        extraLuggage: false,
      },
      {
        id: 9,
        isAvailable: true,
        passengerFirstName: "",
        passengerLastName: "",
        passengerPhoneNumber: "",
        extraLuggage: false,
      },
      {
        id: 10,
        isAvailable: true,
        passengerFirstName: "",
        passengerLastName: "",
        passengerPhoneNumber: "",
        extraLuggage: false,
      },
      {
        id: 11,
        isAvailable: true,
        passengerFirstName: "",
        passengerLastName: "",
        passengerPhoneNumber: "",
        extraLuggage: false,
      },
      {
        id: 12,
        isAvailable: true,
        passengerFirstName: "",
        passengerLastName: "",
        passengerPhoneNumber: "",
        extraLuggage: false,
      },
      {
        id: 13,
        isAvailable: true,
        passengerFirstName: "",
        passengerLastName: "",
        passengerPhoneNumber: "",
        extraLuggage: false,
      },
      {
        id: 14,
        isAvailable: true,
        passengerFirstName: "",
        passengerLastName: "",
        passengerPhoneNumber: "",
        extraLuggage: true,
      },
      {
        id: 15,
        isAvailable: true,
        passengerFirstName: "",
        passengerLastName: "",
        passengerPhoneNumber: "",
        extraLuggage: true,
      },
      {
        id: 16,
        isAvailable: true,
        passengerFirstName: "",
        passengerLastName: "",
        passengerPhoneNumber: "",
        extraLuggage: false,
      },
      {
        id: 17,
        isAvailable: true,
        passengerFirstName: "",
        passengerLastName: "",
        passengerPhoneNumber: "",
        extraLuggage: false,
      },
    ],
  },
  {
    id: 3,
    destination: "Toamasina",
    departureTime: 1613397600,
    driverName: "Brad Pitt",
    driverContact: "034585177",
    estimatedDuration: "7h",
    breaks: "2",
    price: 20000,
    seats: [
      {
        id: 0,
        isAvailable: true,
        passengerFirstName: "",
        passengerLastName: "",
        passengerPhoneNumber: "",
        extraLuggage: false,
      },
      {
        id: 1,
        isAvailable: true,
        passengerFirstName: "",
        passengerLastName: "",
        passengerPhoneNumber: "",
        extraLuggage: false,
      },
      {
        id: 2,
        isAvailable: true,
        passengerFirstName: "",
        passengerLastName: "",
        passengerPhoneNumber: "",
        extraLuggage: false,
      },
      {
        id: 3,
        isAvailable: true,
        passengerFirstName: "",
        passengerLastName: "",
        passengerPhoneNumber: "",
        extraLuggage: false,
      },
      {
        id: 4,
        isAvailable: true,
        passengerFirstName: "",
        passengerLastName: "",
        passengerPhoneNumber: "",
        extraLuggage: false,
      },
      {
        id: 5,
        isAvailable: true,
        passengerFirstName: "",
        passengerLastName: "",
        passengerPhoneNumber: "",
        extraLuggage: false,
      },
      {
        id: 6,
        isAvailable: true,
        passengerFirstName: "",
        passengerLastName: "",
        passengerPhoneNumber: "",
        extraLuggage: false,
      },
      {
        id: 7,
        isAvailable: true,
        passengerFirstName: "",
        passengerLastName: "",
        passengerPhoneNumber: "",
        extraLuggage: false,
      },
      {
        id: 8,
        isAvailable: true,
        passengerFirstName: "",
        passengerLastName: "",
        passengerPhoneNumber: "",
        extraLuggage: false,
      },
      {
        id: 9,
        isAvailable: true,
        passengerFirstName: "",
        passengerLastName: "",
        passengerPhoneNumber: "",
        extraLuggage: false,
      },
      {
        id: 10,
        isAvailable: true,
        passengerFirstName: "",
        passengerLastName: "",
        passengerPhoneNumber: "",
        extraLuggage: false,
      },
      {
        id: 11,
        isAvailable: true,
        passengerFirstName: "",
        passengerLastName: "",
        passengerPhoneNumber: "",
        extraLuggage: false,
      },
      {
        id: 12,
        isAvailable: true,
        passengerFirstName: "",
        passengerLastName: "",
        passengerPhoneNumber: "",
        extraLuggage: false,
      },
      {
        id: 13,
        isAvailable: true,
        passengerFirstName: "",
        passengerLastName: "",
        passengerPhoneNumber: "",
        extraLuggage: false,
      },
      {
        id: 14,
        isAvailable: true,
        passengerFirstName: "",
        passengerLastName: "",
        passengerPhoneNumber: "",
        extraLuggage: true,
      },
      {
        id: 15,
        isAvailable: true,
        passengerFirstName: "",
        passengerLastName: "",
        passengerPhoneNumber: "",
        extraLuggage: true,
      },
      {
        id: 16,
        isAvailable: true,
        passengerFirstName: "",
        passengerLastName: "",
        passengerPhoneNumber: "",
        extraLuggage: false,
      },
      {
        id: 17,
        isAvailable: true,
        passengerFirstName: "",
        passengerLastName: "",
        passengerPhoneNumber: "",
        extraLuggage: false,
      },
    ],
  },
  {
    id: 4,
    destination: "Toamasina",
    departureTime: 1613480400,
    driverName: "Brad Pitt",
    driverContact: "034585177",
    estimatedDuration: "7h",
    breaks: "2",
    price: 10000,
    seats: [
      {
        id: 0,
        isAvailable: false,
        passengerFirstName: "",
        passengerLastName: "",
        passengerPhoneNumber: "",
        extraLuggage: false,
      },
      {
        id: 1,
        isAvailable: false,
        passengerFirstName: "",
        passengerLastName: "",
        passengerPhoneNumber: "",
        extraLuggage: false,
      },
      {
        id: 2,
        isAvailable: false,
        passengerFirstName: "",
        passengerLastName: "",
        passengerPhoneNumber: "",
        extraLuggage: false,
      },
      {
        id: 3,
        isAvailable: false,
        passengerFirstName: "",
        passengerLastName: "",
        passengerPhoneNumber: "",
        extraLuggage: false,
      },
      {
        id: 4,
        isAvailable: false,
        passengerFirstName: "",
        passengerLastName: "",
        passengerPhoneNumber: "",
        extraLuggage: false,
      },
      {
        id: 5,
        isAvailable: false,
        passengerFirstName: "",
        passengerLastName: "",
        passengerPhoneNumber: "",
        extraLuggage: false,
      },
      {
        id: 6,
        isAvailable: false,
        passengerFirstName: "",
        passengerLastName: "",
        passengerPhoneNumber: "",
        extraLuggage: false,
      },
      {
        id: 7,
        isAvailable: false,
        passengerFirstName: "",
        passengerLastName: "",
        passengerPhoneNumber: "",
        extraLuggage: false,
      },
      {
        id: 8,
        isAvailable: false,
        passengerFirstName: "",
        passengerLastName: "",
        passengerPhoneNumber: "",
        extraLuggage: false,
      },
      {
        id: 9,
        isAvailable: false,
        passengerFirstName: "",
        passengerLastName: "",
        passengerPhoneNumber: "",
        extraLuggage: false,
      },
      {
        id: 10,
        isAvailable: false,
        passengerFirstName: "",
        passengerLastName: "",
        passengerPhoneNumber: "",
        extraLuggage: false,
      },
      {
        id: 11,
        isAvailable: false,
        passengerFirstName: "",
        passengerLastName: "",
        passengerPhoneNumber: "",
        extraLuggage: false,
      },
      {
        id: 12,
        isAvailable: false,
        passengerFirstName: "",
        passengerLastName: "",
        passengerPhoneNumber: "",
        extraLuggage: false,
      },
      {
        id: 13,
        isAvailable: false,
        passengerFirstName: "",
        passengerLastName: "",
        passengerPhoneNumber: "",
        extraLuggage: false,
      },
      {
        id: 14,
        isAvailable: false,
        passengerFirstName: "",
        passengerLastName: "",
        passengerPhoneNumber: "",
        extraLuggage: true,
      },
      {
        id: 15,
        isAvailable: false,
        passengerFirstName: "",
        passengerLastName: "",
        passengerPhoneNumber: "",
        extraLuggage: true,
      },
      {
        id: 16,
        isAvailable: false,
        passengerFirstName: "",
        passengerLastName: "",
        passengerPhoneNumber: "",
        extraLuggage: false,
      },
      {
        id: 17,
        isAvailable: false,
        passengerFirstName: "",
        passengerLastName: "",
        passengerPhoneNumber: "",
        extraLuggage: false,
      },
    ],
  },
  {
    id: 5,
    destination: "Vatomandry",
    departureTime: 1613278800,
    driverName: "Brad Pitt",
    driverContact: "034585177",
    estimatedDuration: "5h",
    breaks: "1",
    price: 10000,
    seats: [
      {
        id: 0,
        isAvailable: false,
        passengerFirstName: "",
        passengerLastName: "",
        passengerPhoneNumber: "",
        extraLuggage: false,
      },
      {
        id: 1,
        isAvailable: false,
        passengerFirstName: "",
        passengerLastName: "",
        passengerPhoneNumber: "",
        extraLuggage: false,
      },
      {
        id: 2,
        isAvailable: false,
        passengerFirstName: "",
        passengerLastName: "",
        passengerPhoneNumber: "",
        extraLuggage: false,
      },
      {
        id: 3,
        isAvailable: false,
        passengerFirstName: "",
        passengerLastName: "",
        passengerPhoneNumber: "",
        extraLuggage: false,
      },
      {
        id: 4,
        isAvailable: false,
        passengerFirstName: "",
        passengerLastName: "",
        passengerPhoneNumber: "",
        extraLuggage: false,
      },
      {
        id: 5,
        isAvailable: false,
        passengerFirstName: "",
        passengerLastName: "",
        passengerPhoneNumber: "",
        extraLuggage: false,
      },
      {
        id: 6,
        isAvailable: false,
        passengerFirstName: "",
        passengerLastName: "",
        passengerPhoneNumber: "",
        extraLuggage: false,
      },
      {
        id: 7,
        isAvailable: false,
        passengerFirstName: "",
        passengerLastName: "",
        passengerPhoneNumber: "",
        extraLuggage: false,
      },
      {
        id: 8,
        isAvailable: false,
        passengerFirstName: "",
        passengerLastName: "",
        passengerPhoneNumber: "",
        extraLuggage: false,
      },
      {
        id: 9,
        isAvailable: false,
        passengerFirstName: "",
        passengerLastName: "",
        passengerPhoneNumber: "",
        extraLuggage: false,
      },
      {
        id: 10,
        isAvailable: false,
        passengerFirstName: "",
        passengerLastName: "",
        passengerPhoneNumber: "",
        extraLuggage: false,
      },
      {
        id: 11,
        isAvailable: false,
        passengerFirstName: "",
        passengerLastName: "",
        passengerPhoneNumber: "",
        extraLuggage: false,
      },
      {
        id: 12,
        isAvailable: false,
        passengerFirstName: "",
        passengerLastName: "",
        passengerPhoneNumber: "",
        extraLuggage: false,
      },
      {
        id: 13,
        isAvailable: false,
        passengerFirstName: "",
        passengerLastName: "",
        passengerPhoneNumber: "",
        extraLuggage: false,
      },
      {
        id: 14,
        isAvailable: false,
        passengerFirstName: "",
        passengerLastName: "",
        passengerPhoneNumber: "",
        extraLuggage: true,
      },
      {
        id: 15,
        isAvailable: false,
        passengerFirstName: "",
        passengerLastName: "",
        passengerPhoneNumber: "",
        extraLuggage: true,
      },
      {
        id: 16,
        isAvailable: false,
        passengerFirstName: "",
        passengerLastName: "",
        passengerPhoneNumber: "",
        extraLuggage: false,
      },
      {
        id: 17,
        isAvailable: false,
        passengerFirstName: "",
        passengerLastName: "",
        passengerPhoneNumber: "",
        extraLuggage: false,
      },
    ],
  },
  {
    id: 6,
    destination: "Vatomandry",
    departureTime: 1613397600,
    driverName: "Brad Pitt",
    driverContact: "034585177",
    estimatedDuration: "5h",
    breaks: "1",
    price: 10000,
    seats: [
      {
        id: 0,
        isAvailable: false,
        passengerFirstName: "",
        passengerLastName: "",
        passengerPhoneNumber: "",
        extraLuggage: false,
      },
      {
        id: 1,
        isAvailable: false,
        passengerFirstName: "",
        passengerLastName: "",
        passengerPhoneNumber: "",
        extraLuggage: false,
      },
      {
        id: 2,
        isAvailable: false,
        passengerFirstName: "",
        passengerLastName: "",
        passengerPhoneNumber: "",
        extraLuggage: false,
      },
      {
        id: 3,
        isAvailable: false,
        passengerFirstName: "",
        passengerLastName: "",
        passengerPhoneNumber: "",
        extraLuggage: false,
      },
      {
        id: 4,
        isAvailable: false,
        passengerFirstName: "",
        passengerLastName: "",
        passengerPhoneNumber: "",
        extraLuggage: false,
      },
      {
        id: 5,
        isAvailable: false,
        passengerFirstName: "",
        passengerLastName: "",
        passengerPhoneNumber: "",
        extraLuggage: false,
      },
      {
        id: 6,
        isAvailable: false,
        passengerFirstName: "",
        passengerLastName: "",
        passengerPhoneNumber: "",
        extraLuggage: false,
      },
      {
        id: 7,
        isAvailable: false,
        passengerFirstName: "",
        passengerLastName: "",
        passengerPhoneNumber: "",
        extraLuggage: false,
      },
      {
        id: 8,
        isAvailable: false,
        passengerFirstName: "",
        passengerLastName: "",
        passengerPhoneNumber: "",
        extraLuggage: false,
      },
      {
        id: 9,
        isAvailable: false,
        passengerFirstName: "",
        passengerLastName: "",
        passengerPhoneNumber: "",
        extraLuggage: false,
      },
      {
        id: 10,
        isAvailable: false,
        passengerFirstName: "",
        passengerLastName: "",
        passengerPhoneNumber: "",
        extraLuggage: false,
      },
      {
        id: 11,
        isAvailable: true,
        passengerFirstName: "",
        passengerLastName: "",
        passengerPhoneNumber: "",
        extraLuggage: false,
      },
      {
        id: 12,
        isAvailable: true,
        passengerFirstName: "",
        passengerLastName: "",
        passengerPhoneNumber: "",
        extraLuggage: false,
      },
      {
        id: 13,
        isAvailable: true,
        passengerFirstName: "",
        passengerLastName: "",
        passengerPhoneNumber: "",
        extraLuggage: false,
      },
      {
        id: 14,
        isAvailable: true,
        passengerFirstName: "",
        passengerLastName: "",
        passengerPhoneNumber: "",
        extraLuggage: true,
      },
      {
        id: 15,
        isAvailable: true,
        passengerFirstName: "",
        passengerLastName: "",
        passengerPhoneNumber: "",
        extraLuggage: true,
      },
      {
        id: 16,
        isAvailable: true,
        passengerFirstName: "",
        passengerLastName: "",
        passengerPhoneNumber: "",
        extraLuggage: false,
      },
      {
        id: 17,
        isAvailable: true,
        passengerFirstName: "",
        passengerLastName: "",
        passengerPhoneNumber: "",
        extraLuggage: false,
      },
    ],
  },
  {
    id: 7,
    destination: "Vatomandry",
    departureTime: 1613570400,
    driverName: "Brad Pitt",
    driverContact: "034585177",
    estimatedDuration: "5h",
    breaks: "1",
    price: 10000,
    seats: [
      {
        id: 0,
        isAvailable: true,
        passengerFirstName: "",
        passengerLastName: "",
        passengerPhoneNumber: "",
        extraLuggage: false,
      },
      {
        id: 1,
        isAvailable: true,
        passengerFirstName: "",
        passengerLastName: "",
        passengerPhoneNumber: "",
        extraLuggage: false,
      },
      {
        id: 2,
        isAvailable: true,
        passengerFirstName: "",
        passengerLastName: "",
        passengerPhoneNumber: "",
        extraLuggage: false,
      },
      {
        id: 3,
        isAvailable: true,
        passengerFirstName: "",
        passengerLastName: "",
        passengerPhoneNumber: "",
        extraLuggage: false,
      },
      {
        id: 4,
        isAvailable: true,
        passengerFirstName: "",
        passengerLastName: "",
        passengerPhoneNumber: "",
        extraLuggage: false,
      },
      {
        id: 5,
        isAvailable: true,
        passengerFirstName: "",
        passengerLastName: "",
        passengerPhoneNumber: "",
        extraLuggage: false,
      },
      {
        id: 6,
        isAvailable: true,
        passengerFirstName: "",
        passengerLastName: "",
        passengerPhoneNumber: "",
        extraLuggage: false,
      },
      {
        id: 7,
        isAvailable: true,
        passengerFirstName: "",
        passengerLastName: "",
        passengerPhoneNumber: "",
        extraLuggage: false,
      },
      {
        id: 8,
        isAvailable: true,
        passengerFirstName: "",
        passengerLastName: "",
        passengerPhoneNumber: "",
        extraLuggage: false,
      },
      {
        id: 9,
        isAvailable: true,
        passengerFirstName: "",
        passengerLastName: "",
        passengerPhoneNumber: "",
        extraLuggage: false,
      },
      {
        id: 10,
        isAvailable: true,
        passengerFirstName: "",
        passengerLastName: "",
        passengerPhoneNumber: "",
        extraLuggage: false,
      },
      {
        id: 11,
        isAvailable: true,
        passengerFirstName: "",
        passengerLastName: "",
        passengerPhoneNumber: "",
        extraLuggage: false,
      },
      {
        id: 12,
        isAvailable: true,
        passengerFirstName: "",
        passengerLastName: "",
        passengerPhoneNumber: "",
        extraLuggage: false,
      },
      {
        id: 13,
        isAvailable: true,
        passengerFirstName: "",
        passengerLastName: "",
        passengerPhoneNumber: "",
        extraLuggage: false,
      },
      {
        id: 14,
        isAvailable: true,
        passengerFirstName: "",
        passengerLastName: "",
        passengerPhoneNumber: "",
        extraLuggage: true,
      },
      {
        id: 15,
        isAvailable: true,
        passengerFirstName: "",
        passengerLastName: "",
        passengerPhoneNumber: "",
        extraLuggage: true,
      },
      {
        id: 16,
        isAvailable: true,
        passengerFirstName: "",
        passengerLastName: "",
        passengerPhoneNumber: "",
        extraLuggage: false,
      },
      {
        id: 17,
        isAvailable: true,
        passengerFirstName: "",
        passengerLastName: "",
        passengerPhoneNumber: "",
        extraLuggage: false,
      },
    ],
  },
  {
    id: 8,
    destination: "Moramanga",
    departureTime: 1613570400,
    driverName: "James Bond",
    driverContact: "034585177",
    estimatedDuration: "6h",
    breaks: "1",
    price: 15000,
    seats: [
      {
        id: 0,
        isAvailable: true,
        passengerFirstName: "",
        passengerLastName: "",
        passengerPhoneNumber: "",
        extraLuggage: false,
      },
      {
        id: 1,
        isAvailable: true,
        passengerFirstName: "",
        passengerLastName: "",
        passengerPhoneNumber: "",
        extraLuggage: false,
      },
      {
        id: 2,
        isAvailable: true,
        passengerFirstName: "",
        passengerLastName: "",
        passengerPhoneNumber: "",
        extraLuggage: false,
      },
      {
        id: 3,
        isAvailable: true,
        passengerFirstName: "",
        passengerLastName: "",
        passengerPhoneNumber: "",
        extraLuggage: false,
      },
      {
        id: 4,
        isAvailable: true,
        passengerFirstName: "",
        passengerLastName: "",
        passengerPhoneNumber: "",
        extraLuggage: false,
      },
      {
        id: 5,
        isAvailable: true,
        passengerFirstName: "",
        passengerLastName: "",
        passengerPhoneNumber: "",
        extraLuggage: false,
      },
      {
        id: 6,
        isAvailable: true,
        passengerFirstName: "",
        passengerLastName: "",
        passengerPhoneNumber: "",
        extraLuggage: false,
      },
      {
        id: 7,
        isAvailable: false,
        passengerFirstName: "",
        passengerLastName: "",
        passengerPhoneNumber: "",
        extraLuggage: false,
      },
      {
        id: 8,
        isAvailable: false,
        passengerFirstName: "",
        passengerLastName: "",
        passengerPhoneNumber: "",
        extraLuggage: false,
      },
      {
        id: 9,
        isAvailable: false,
        passengerFirstName: "",
        passengerLastName: "",
        passengerPhoneNumber: "",
        extraLuggage: false,
      },
      {
        id: 10,
        isAvailable: false,
        passengerFirstName: "",
        passengerLastName: "",
        passengerPhoneNumber: "",
        extraLuggage: false,
      },
      {
        id: 11,
        isAvailable: false,
        passengerFirstName: "",
        passengerLastName: "",
        passengerPhoneNumber: "",
        extraLuggage: false,
      },
      {
        id: 12,
        isAvailable: false,
        passengerFirstName: "",
        passengerLastName: "",
        passengerPhoneNumber: "",
        extraLuggage: false,
      },
      {
        id: 13,
        isAvailable: false,
        passengerFirstName: "",
        passengerLastName: "",
        passengerPhoneNumber: "",
        extraLuggage: false,
      },
      {
        id: 14,
        isAvailable: false,
        passengerFirstName: "",
        passengerLastName: "",
        passengerPhoneNumber: "",
        extraLuggage: true,
      },
      {
        id: 15,
        isAvailable: false,
        passengerFirstName: "",
        passengerLastName: "",
        passengerPhoneNumber: "",
        extraLuggage: true,
      },
      {
        id: 16,
        isAvailable: false,
        passengerFirstName: "",
        passengerLastName: "",
        passengerPhoneNumber: "",
        extraLuggage: false,
      },
      {
        id: 17,
        isAvailable: false,
        passengerFirstName: "",
        passengerLastName: "",
        passengerPhoneNumber: "",
        extraLuggage: false,
      },
    ],
  },
  {
    id: 9,
    destination: "Moramanga",
    departureTime: 1613656800,
    driverName: "James Bond",
    driverContact: "034585177",
    estimatedDuration: "6h",
    breaks: "1",
    price: 15000,
    seats: [
      {
        id: 0,
        isAvailable: false,
        passengerFirstName: "",
        passengerLastName: "",
        passengerPhoneNumber: "",
        extraLuggage: false,
      },
      {
        id: 1,
        isAvailable: false,
        passengerFirstName: "",
        passengerLastName: "",
        passengerPhoneNumber: "",
        extraLuggage: false,
      },
      {
        id: 2,
        isAvailable: false,
        passengerFirstName: "",
        passengerLastName: "",
        passengerPhoneNumber: "",
        extraLuggage: false,
      },
      {
        id: 3,
        isAvailable: false,
        passengerFirstName: "",
        passengerLastName: "",
        passengerPhoneNumber: "",
        extraLuggage: false,
      },
      {
        id: 4,
        isAvailable: false,
        passengerFirstName: "",
        passengerLastName: "",
        passengerPhoneNumber: "",
        extraLuggage: false,
      },
      {
        id: 5,
        isAvailable: false,
        passengerFirstName: "",
        passengerLastName: "",
        passengerPhoneNumber: "",
        extraLuggage: false,
      },
      {
        id: 6,
        isAvailable: false,
        passengerFirstName: "",
        passengerLastName: "",
        passengerPhoneNumber: "",
        extraLuggage: false,
      },
      {
        id: 7,
        isAvailable: false,
        passengerFirstName: "",
        passengerLastName: "",
        passengerPhoneNumber: "",
        extraLuggage: false,
      },
      {
        id: 8,
        isAvailable: false,
        passengerFirstName: "",
        passengerLastName: "",
        passengerPhoneNumber: "",
        extraLuggage: false,
      },
      {
        id: 9,
        isAvailable: false,
        passengerFirstName: "",
        passengerLastName: "",
        passengerPhoneNumber: "",
        extraLuggage: false,
      },
      {
        id: 10,
        isAvailable: false,
        passengerFirstName: "",
        passengerLastName: "",
        passengerPhoneNumber: "",
        extraLuggage: false,
      },
      {
        id: 11,
        isAvailable: false,
        passengerFirstName: "",
        passengerLastName: "",
        passengerPhoneNumber: "",
        extraLuggage: false,
      },
      {
        id: 12,
        isAvailable: false,
        passengerFirstName: "",
        passengerLastName: "",
        passengerPhoneNumber: "",
        extraLuggage: false,
      },
      {
        id: 13,
        isAvailable: false,
        passengerFirstName: "",
        passengerLastName: "",
        passengerPhoneNumber: "",
        extraLuggage: false,
      },
      {
        id: 14,
        isAvailable: false,
        passengerFirstName: "",
        passengerLastName: "",
        passengerPhoneNumber: "",
        extraLuggage: true,
      },
      {
        id: 15,
        isAvailable: false,
        passengerFirstName: "",
        passengerLastName: "",
        passengerPhoneNumber: "",
        extraLuggage: true,
      },
      {
        id: 16,
        isAvailable: false,
        passengerFirstName: "",
        passengerLastName: "",
        passengerPhoneNumber: "",
        extraLuggage: false,
      },
      {
        id: 17,
        isAvailable: false,
        passengerFirstName: "",
        passengerLastName: "",
        passengerPhoneNumber: "",
        extraLuggage: false,
      },
    ],
  },
  {
    id: 10,
    destination: "Moramanga",
    departureTime: 1613743200,
    driverName: "James Bond",
    driverContact: "034585177",
    estimatedDuration: "6h",
    breaks: "1",
    price: 15000,
    seats: [
      {
        id: 0,
        isAvailable: true,
        passengerFirstName: "",
        passengerLastName: "",
        passengerPhoneNumber: "",
        extraLuggage: false,
      },
      {
        id: 1,
        isAvailable: true,
        passengerFirstName: "",
        passengerLastName: "",
        passengerPhoneNumber: "",
        extraLuggage: false,
      },
      {
        id: 2,
        isAvailable: true,
        passengerFirstName: "",
        passengerLastName: "",
        passengerPhoneNumber: "",
        extraLuggage: false,
      },
      {
        id: 3,
        isAvailable: true,
        passengerFirstName: "",
        passengerLastName: "",
        passengerPhoneNumber: "",
        extraLuggage: false,
      },
      {
        id: 4,
        isAvailable: true,
        passengerFirstName: "",
        passengerLastName: "",
        passengerPhoneNumber: "",
        extraLuggage: false,
      },
      {
        id: 5,
        isAvailable: true,
        passengerFirstName: "",
        passengerLastName: "",
        passengerPhoneNumber: "",
        extraLuggage: false,
      },
      {
        id: 6,
        isAvailable: true,
        passengerFirstName: "",
        passengerLastName: "",
        passengerPhoneNumber: "",
        extraLuggage: false,
      },
      {
        id: 7,
        isAvailable: true,
        passengerFirstName: "",
        passengerLastName: "",
        passengerPhoneNumber: "",
        extraLuggage: false,
      },
      {
        id: 8,
        isAvailable: true,
        passengerFirstName: "",
        passengerLastName: "",
        passengerPhoneNumber: "",
        extraLuggage: false,
      },
      {
        id: 9,
        isAvailable: true,
        passengerFirstName: "",
        passengerLastName: "",
        passengerPhoneNumber: "",
        extraLuggage: false,
      },
      {
        id: 10,
        isAvailable: true,
        passengerFirstName: "",
        passengerLastName: "",
        passengerPhoneNumber: "",
        extraLuggage: false,
      },
      {
        id: 11,
        isAvailable: true,
        passengerFirstName: "",
        passengerLastName: "",
        passengerPhoneNumber: "",
        extraLuggage: false,
      },
      {
        id: 12,
        isAvailable: true,
        passengerFirstName: "",
        passengerLastName: "",
        passengerPhoneNumber: "",
        extraLuggage: false,
      },
      {
        id: 13,
        isAvailable: true,
        passengerFirstName: "",
        passengerLastName: "",
        passengerPhoneNumber: "",
        extraLuggage: false,
      },
      {
        id: 14,
        isAvailable: true,
        passengerFirstName: "",
        passengerLastName: "",
        passengerPhoneNumber: "",
        extraLuggage: true,
      },
      {
        id: 15,
        isAvailable: true,
        passengerFirstName: "",
        passengerLastName: "",
        passengerPhoneNumber: "",
        extraLuggage: true,
      },
      {
        id: 16,
        isAvailable: true,
        passengerFirstName: "",
        passengerLastName: "",
        passengerPhoneNumber: "",
        extraLuggage: false,
      },
      {
        id: 17,
        isAvailable: true,
        passengerFirstName: "",
        passengerLastName: "",
        passengerPhoneNumber: "",
        extraLuggage: false,
      },
    ],
  },
  {
    id: 11,
    destination: "Moramanga",
    departureTime: 1613829600,
    driverName: "James Bond",
    driverContact: "034585177",
    estimatedDuration: "6h",
    breaks: "1",
    price: 15000,
    seats: [
      {
        id: 0,
        isAvailable: true,
        passengerFirstName: "",
        passengerLastName: "",
        passengerPhoneNumber: "",
        extraLuggage: false,
      },
      {
        id: 1,
        isAvailable: true,
        passengerFirstName: "",
        passengerLastName: "",
        passengerPhoneNumber: "",
        extraLuggage: false,
      },
      {
        id: 2,
        isAvailable: true,
        passengerFirstName: "",
        passengerLastName: "",
        passengerPhoneNumber: "",
        extraLuggage: false,
      },
      {
        id: 3,
        isAvailable: true,
        passengerFirstName: "",
        passengerLastName: "",
        passengerPhoneNumber: "",
        extraLuggage: false,
      },
      {
        id: 4,
        isAvailable: true,
        passengerFirstName: "",
        passengerLastName: "",
        passengerPhoneNumber: "",
        extraLuggage: false,
      },
      {
        id: 5,
        isAvailable: true,
        passengerFirstName: "",
        passengerLastName: "",
        passengerPhoneNumber: "",
        extraLuggage: false,
      },
      {
        id: 6,
        isAvailable: true,
        passengerFirstName: "",
        passengerLastName: "",
        passengerPhoneNumber: "",
        extraLuggage: false,
      },
      {
        id: 7,
        isAvailable: true,
        passengerFirstName: "",
        passengerLastName: "",
        passengerPhoneNumber: "",
        extraLuggage: false,
      },
      {
        id: 8,
        isAvailable: true,
        passengerFirstName: "",
        passengerLastName: "",
        passengerPhoneNumber: "",
        extraLuggage: false,
      },
      {
        id: 9,
        isAvailable: true,
        passengerFirstName: "",
        passengerLastName: "",
        passengerPhoneNumber: "",
        extraLuggage: false,
      },
      {
        id: 10,
        isAvailable: true,
        passengerFirstName: "",
        passengerLastName: "",
        passengerPhoneNumber: "",
        extraLuggage: false,
      },
      {
        id: 11,
        isAvailable: true,
        passengerFirstName: "",
        passengerLastName: "",
        passengerPhoneNumber: "",
        extraLuggage: false,
      },
      {
        id: 12,
        isAvailable: true,
        passengerFirstName: "",
        passengerLastName: "",
        passengerPhoneNumber: "",
        extraLuggage: false,
      },
      {
        id: 13,
        isAvailable: true,
        passengerFirstName: "",
        passengerLastName: "",
        passengerPhoneNumber: "",
        extraLuggage: false,
      },
      {
        id: 14,
        isAvailable: true,
        passengerFirstName: "",
        passengerLastName: "",
        passengerPhoneNumber: "",
        extraLuggage: true,
      },
      {
        id: 15,
        isAvailable: true,
        passengerFirstName: "",
        passengerLastName: "",
        passengerPhoneNumber: "",
        extraLuggage: true,
      },
      {
        id: 16,
        isAvailable: true,
        passengerFirstName: "",
        passengerLastName: "",
        passengerPhoneNumber: "",
        extraLuggage: false,
      },
      {
        id: 17,
        isAvailable: true,
        passengerFirstName: "",
        passengerLastName: "",
        passengerPhoneNumber: "",
        extraLuggage: false,
      },
    ],
  },
]
};
